{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ledgermem.fullname" . }}-api
  labels:
    {{- include "ledgermem.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "ledgermem.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
