{{- if .Values.apiKey.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledgermem.fullname" . }}-api-key
  labels:
    {{- include "ledgermem.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ randAlphaNum 40 | quote }}
{{- end }}
{{- if .Values.licenseKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledgermem.fullname" . }}-license
  labels:
    {{- include "ledgermem.labels" . | nindent 4 }}
type: Opaque
stringData:
  license: {{ .Values.licenseKey | quote }}
{{- end }}
