{{- if .Values.monitoring.serviceMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "getmnemo.fullname" . }}
  labels:
    {{- include "getmnemo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "getmnemo.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
